// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260518220038_UpdateDbContextChanges")]
    partial class UpdateDbContextChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            Category = "Electronics",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest Samsung flagship with AI-powered camera and all-day battery life.",
                            DiscountPercent = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Samsung Galaxy S24",
                            OriginalPrice = 209999m,
                            Price = 189999m,
                            Rating = 4.5m,
                            ReviewCount = 128,
                            SellerId = 1,
                            Sku = "EL-001",
                            Stock = 45,
                            Tags = "smartphone,android,samsung"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Category = "Electronics",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra-thin laptop with Apple M3 chip. 18 hours battery life, fanless design.",
                            DiscountPercent = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Apple MacBook Air M3",
                            OriginalPrice = 379999m,
                            Price = 349999m,
                            Rating = 4.8m,
                            ReviewCount = 256,
                            SellerId = 1,
                            Sku = "EL-002",
                            Stock = 22,
                            Tags = "laptop,apple,macbook"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Sony",
                            Category = "Electronics",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Industry-leading noise cancellation with 30-hour battery and crystal-clear calls.",
                            DiscountPercent = 18,
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Sony WH-1000XM5 Headphones",
                            OriginalPrice = 79999m,
                            Price = 65999m,
                            Rating = 4.7m,
                            ReviewCount = 412,
                            SellerId = 1,
                            Sku = "EL-003",
                            Stock = 60,
                            Tags = "headphones,sony,noise-cancelling"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nike",
                            Category = "Fashion",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inspired by two iconic Air Max models, the 270 delivers unrivaled comfort.",
                            DiscountPercent = 22,
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Nike Air Max 270",
                            OriginalPrice = 31999m,
                            Price = 24999m,
                            Rating = 4.4m,
                            ReviewCount = 189,
                            SellerId = 1,
                            Sku = "FA-001",
                            Stock = 85,
                            Tags = "shoes,nike,running"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Levis",
                            Category = "Fashion",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The original straight fit jean with button fly. The jeans that started it all.",
                            DiscountPercent = 25,
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Levi's 501 Original Jeans",
                            OriginalPrice = 11999m,
                            Price = 8999m,
                            Rating = 4.3m,
                            ReviewCount = 95,
                            SellerId = 1,
                            Sku = "FA-002",
                            Stock = 120,
                            Tags = "jeans,levis,fashion"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Instant Pot",
                            Category = "Home & Kitchen",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-use pressure cooker, slow cooker, rice cooker, steamer, sauté, and warmer.",
                            DiscountPercent = 21,
                            ImageUrl = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Instant Pot Duo 7-in-1",
                            OriginalPrice = 23999m,
                            Price = 18999m,
                            Rating = 4.6m,
                            ReviewCount = 342,
                            SellerId = 1,
                            Sku = "HK-001",
                            Stock = 35,
                            Tags = "kitchen,cooking,appliance"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "LifeFit",
                            Category = "Sports & Outdoors",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extra thick 6mm exercise mat with superior grip. Ideal for yoga, pilates, and stretching.",
                            DiscountPercent = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1601925228010-f9c19985bee7?w=400",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Yoga Mat Premium Non-Slip",
                            Price = 3499m,
                            Rating = 4.2m,
                            ReviewCount = 67,
                            SellerId = 1,
                            Sku = "SP-001",
                            Stock = 200,
                            Tags = "yoga,fitness,mat"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Addison-Wesley",
                            Category = "Books",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "From journeyman to master — timeless wisdom for software developers.",
                            DiscountPercent = 20,
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "The Pragmatic Programmer",
                            OriginalPrice = 4999m,
                            Price = 3999m,
                            Rating = 4.9m,
                            ReviewCount = 512,
                            SellerId = 1,
                            Sku = "BK-001",
                            Stock = 75,
                            Tags = "programming,books,software"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Canon",
                            Category = "Electronics",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "24.2MP APS-C mirrorless with dual pixel autofocus and 4K video.",
                            DiscountPercent = 13,
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Canon EOS R50 Mirrorless Camera",
                            OriginalPrice = 149999m,
                            Price = 129999m,
                            Rating = 4.6m,
                            ReviewCount = 78,
                            SellerId = 1,
                            Sku = "EL-004",
                            Stock = 15,
                            Tags = "camera,canon,photography"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Logitech",
                            Category = "Electronics",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced wireless mouse with MagSpeed scroll wheel and customizable buttons.",
                            DiscountPercent = 17,
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Logitech MX Master 3S Mouse",
                            OriginalPrice = 17999m,
                            Price = 14999m,
                            Rating = 4.7m,
                            ReviewCount = 223,
                            SellerId = 1,
                            Sku = "EL-005",
                            Stock = 90,
                            Tags = "mouse,logitech,wireless"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Dyson",
                            Category = "Home & Kitchen",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laser detects hidden dust. Piezo sensor counts and sizes particles in real time.",
                            DiscountPercent = 18,
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Dyson V15 Detect Vacuum",
                            OriginalPrice = 109999m,
                            Price = 89999m,
                            Rating = 4.5m,
                            ReviewCount = 134,
                            SellerId = 1,
                            Sku = "HK-002",
                            Stock = 12,
                            Tags = "vacuum,dyson,cleaning"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Adidas",
                            Category = "Fashion",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Energy-returning Boost midsole in a Primeknit+ upper. Run further, feel better.",
                            DiscountPercent = 18,
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Adidas Ultraboost 22",
                            OriginalPrice = 27999m,
                            Price = 22999m,
                            Rating = 4.4m,
                            ReviewCount = 167,
                            SellerId = 1,
                            Sku = "FA-003",
                            Stock = 55,
                            Tags = "shoes,adidas,running"
                        });
                });

            modelBuilder.Entity("ProductService.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ProductService.Models.ProductImage", b =>
                {
                    b.HasOne("ProductService.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
