// services/ProductService/Migrations/20260522000003_AddProductReviews.Designer.cs

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260522000003_AddProductReviews")]
    partial class AddProductReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.ProductReview", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<int>("BuyerId")
                    .HasColumnType("int");

                b.Property<string>("BuyerName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsVisible")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(true)
                    .HasColumnType("bit");

                b.Property<string>("ModeratorNote")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int?>("OrderId")
                    .HasColumnType("int");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<int>("Rating")
                    .HasColumnType("int");

                b.Property<string>("SellerReply")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<DateTime?>("SellerRepliedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("SellerRepliedById")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("UpdatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("BuyerId");

                b.HasIndex("IsVisible");

                b.HasIndex("ProductId");

                b.HasIndex("ProductId", "BuyerId")
                    .IsUnique();

                b.ToTable("ProductReviews");
            });

            modelBuilder.Entity("ProductService.Models.ProductReview", b =>
            {
                b.HasOne("ProductService.Models.Product", "Product")
                    .WithMany("Reviews")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });
#pragma warning restore 612, 618
        }
    }
}