// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260518220133_UpdateDbContextChanges")]
    partial class UpdateDbContextChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            CustomerName = "Carol White",
                            DeliveredAt = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Discount = 0m,
                            EstimatedDelivery = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "COD",
                            PaymentStatus = "Paid",
                            ShippingFee = 0m,
                            Status = "Completed",
                            Total = 255998m,
                            TrackingNumber = "DH-001-2024"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            CustomerName = "Carol White",
                            Discount = 0m,
                            EstimatedDelivery = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "EasyPaisa",
                            PaymentStatus = "Paid",
                            ShippingFee = 0m,
                            Status = "Processing",
                            Total = 65999m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            CustomerName = "David Khan",
                            Discount = 0m,
                            PaymentMethod = "COD",
                            PaymentStatus = "Pending",
                            ShippingFee = 0m,
                            Status = "Pending",
                            Total = 32498m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            CustomerName = "David Khan",
                            Discount = 0m,
                            PaymentMethod = "Card",
                            PaymentStatus = "Refunded",
                            ShippingFee = 0m,
                            Status = "Cancelled",
                            Total = 24999m
                        });
                });

            modelBuilder.Entity("OrderService.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            ProductName = "Samsung Galaxy S24",
                            Quantity = 1,
                            UnitPrice = 189999m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 10,
                            ProductName = "Logitech MX Master 3S Mouse",
                            Quantity = 1,
                            UnitPrice = 14999m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 8,
                            ProductName = "The Pragmatic Programmer",
                            Quantity = 1,
                            UnitPrice = 3999m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 3,
                            ProductName = "Sony WH-1000XM5 Headphones",
                            Quantity = 1,
                            UnitPrice = 65999m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 4,
                            ProductName = "Nike Air Max 270",
                            Quantity = 1,
                            UnitPrice = 24999m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 7,
                            ProductName = "Yoga Mat Premium Non-Slip",
                            Quantity = 2,
                            UnitPrice = 3499m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 12,
                            ProductName = "Adidas Ultraboost 22",
                            Quantity = 1,
                            UnitPrice = 24999m
                        });
                });

            modelBuilder.Entity("OrderService.Models.OrderLine", b =>
                {
                    b.HasOne("OrderService.Models.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
