// <auto-generated />
using System;
using CategoryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoryService.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20260518220313_UpdateDbContextChanges")]
    partial class UpdateDbContextChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phones, laptops, accessories and more",
                            IsActive = true,
                            Name = "Electronics",
                            Slug = "electronics",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing, shoes, and accessories",
                            IsActive = true,
                            Name = "Fashion",
                            Slug = "fashion",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Furniture, appliances, and decor",
                            IsActive = true,
                            Name = "Home & Kitchen",
                            Slug = "home-kitchen",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sports gear and outdoor equipment",
                            IsActive = true,
                            Name = "Sports & Outdoors",
                            Slug = "sports-outdoors",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fiction, non-fiction, textbooks",
                            IsActive = true,
                            Name = "Books",
                            Slug = "books",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Skincare, makeup, and fragrances",
                            IsActive = true,
                            Name = "Beauty",
                            Slug = "beauty",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toys, board games, and video games",
                            IsActive = true,
                            Name = "Toys & Games",
                            Slug = "toys-games",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Car accessories and tools",
                            IsActive = true,
                            Name = "Automotive",
                            Slug = "automotive",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Android and iOS phones",
                            IsActive = true,
                            Name = "Smartphones",
                            ParentId = 1,
                            Slug = "smartphones",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notebooks and ultrabooks",
                            IsActive = true,
                            Name = "Laptops",
                            ParentId = 1,
                            Slug = "laptops",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Headphones, speakers, earbuds",
                            IsActive = true,
                            Name = "Audio",
                            ParentId = 1,
                            Slug = "audio",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DSLR, mirrorless, and action cameras",
                            IsActive = true,
                            Name = "Cameras",
                            ParentId = 1,
                            Slug = "cameras",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("CategoryService.Models.Category", b =>
                {
                    b.HasOne("CategoryService.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CategoryService.Models.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
