// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WishlistService.Data;

#nullable disable

namespace WishlistService.Migrations
{
    [DbContext(typeof(WishlistDbContext))]
    partial class WishlistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WishlistService.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            ProductImage = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
                            ProductName = "Apple MacBook Air M3",
                            ProductPrice = 349999m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 9,
                            ProductImage = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
                            ProductName = "Canon EOS R50 Mirrorless Camera",
                            ProductPrice = 129999m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 11,
                            ProductImage = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            ProductName = "Dyson V15 Detect Vacuum",
                            ProductPrice = 89999m,
                            UserId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
